-- ============================================
-- GenoMAX² Bloodwork Safety Routing System
-- Migration: 013_bloodwork_safety_routing
-- Version: bloodwork_v2.0
-- 
-- Connects 31 safety gates to ingredient-level routing
-- "Blood does not negotiate" - deterministic constraint enforcement
-- ============================================

-- Enable UUID generation if not already enabled
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================
-- ENUM Types for Safety Routing
-- ============================================

-- Gate tier classification
DO $$ BEGIN
    CREATE TYPE gate_tier AS ENUM ('TIER1_SAFETY', 'TIER2_OPTIMIZATION', 'TIER3_GENETIC_HORMONAL');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Gate action types
DO $$ BEGIN
    CREATE TYPE gate_action AS ENUM ('BLOCK', 'CAUTION', 'FLAG');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- ============================================
-- Table: bloodwork_safety_gates
-- Master list of all 31 safety gates with routing metadata
-- ============================================
CREATE TABLE IF NOT EXISTS bloodwork_safety_gates (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Gate identification
    gate_code TEXT NOT NULL UNIQUE,        -- e.g., 'GATE_001', 'GATE_014'
    gate_name TEXT NOT NULL,               -- e.g., 'iron_block', 'coagulation_caution'
    display_name TEXT NOT NULL,            -- Human-readable name
    
    -- Classification
    tier gate_tier NOT NULL,
    action gate_action NOT NULL,
    
    -- Constraint codes generated by engine
    constraint_code TEXT NOT NULL,         -- e.g., 'BLOCK_IRON', 'CAUTION_HEPATOTOXIC'
    
    -- Clinical context
    description TEXT,                      -- Clinical rationale
    biomarker_triggers TEXT[],             -- e.g., ['ferritin', 'hs_crp']
    
    -- Routing behavior
    blocks_ingredients BOOLEAN DEFAULT FALSE,
    cautions_ingredients BOOLEAN DEFAULT FALSE,
    recommends_ingredients BOOLEAN DEFAULT FALSE,
    
    -- Exception handling
    exception_conditions JSONB,            -- e.g., {"deferred_if": "hs_crp > 3.0"}
    
    -- Metadata
    version TEXT NOT NULL DEFAULT '2.0',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for safety gate lookups
CREATE INDEX IF NOT EXISTS idx_safety_gates_code ON bloodwork_safety_gates (gate_code);
CREATE INDEX IF NOT EXISTS idx_safety_gates_name ON bloodwork_safety_gates (gate_name);
CREATE INDEX IF NOT EXISTS idx_safety_gates_constraint ON bloodwork_safety_gates (constraint_code);
CREATE INDEX IF NOT EXISTS idx_safety_gates_tier ON bloodwork_safety_gates (tier);
CREATE INDEX IF NOT EXISTS idx_safety_gates_action ON bloodwork_safety_gates (action);

-- ============================================
-- Table: ingredient_safety_flags
-- Maps ingredients to safety constraints (M:N relationship)
-- ============================================
CREATE TABLE IF NOT EXISTS ingredient_safety_flags (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Ingredient identification (matches os_modules or ingredient tables)
    ingredient_code TEXT NOT NULL,          -- Canonical ingredient code
    ingredient_name TEXT NOT NULL,          -- Display name
    
    -- Safety constraint mapping
    constraint_code TEXT NOT NULL,          -- e.g., 'BLOCK_IRON', 'CAUTION_HEPATOTOXIC'
    flag_type TEXT NOT NULL CHECK (flag_type IN ('BLOCKED', 'CAUTION', 'RECOMMENDED')),
    
    -- Dosage context (optional)
    threshold_mg DECIMAL,                   -- Above this dose, constraint applies
    per_serving BOOLEAN DEFAULT TRUE,
    
    -- Clinical notes
    rationale TEXT,                         -- Why this ingredient triggers this flag
    
    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    -- Prevent duplicates
    CONSTRAINT unique_ingredient_constraint UNIQUE (ingredient_code, constraint_code)
);

-- Indexes for ingredient safety lookups
CREATE INDEX IF NOT EXISTS idx_ingredient_safety_code ON ingredient_safety_flags (ingredient_code);
CREATE INDEX IF NOT EXISTS idx_ingredient_safety_constraint ON ingredient_safety_flags (constraint_code);
CREATE INDEX IF NOT EXISTS idx_ingredient_safety_type ON ingredient_safety_flags (flag_type);

-- ============================================
-- Table: bloodwork_user_results
-- Stores processed bloodwork results per user
-- ============================================
CREATE TABLE IF NOT EXISTS bloodwork_user_results (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- User identification
    user_id TEXT NOT NULL,                  -- External user ID
    
    -- Test metadata
    test_date DATE NOT NULL,
    lab_profile TEXT DEFAULT 'GLOBAL_CONSERVATIVE',
    source TEXT CHECK (source IN ('ocr_upload', 'manual_entry', 'lab_api', 'user_upload')),
    
    -- Raw input
    raw_markers JSONB NOT NULL,             -- Original marker values as submitted
    
    -- Processed output from BloodworkEngineV2
    processed_result JSONB NOT NULL,        -- Full BloodworkResult object
    
    -- Summary for quick queries
    active_gates TEXT[],                    -- Array of triggered gate codes
    blocked_ingredients TEXT[],             -- Ingredients blocked by gates
    caution_ingredients TEXT[],             -- Ingredients requiring caution
    recommended_ingredients TEXT[],         -- Ingredients recommended by gates
    
    -- Computed markers (if calculated)
    computed_markers JSONB,                 -- HOMA-IR, ratios, etc.
    
    -- Engine metadata
    engine_version TEXT NOT NULL,           -- e.g., '2.0.0'
    ruleset_version TEXT NOT NULL,          -- e.g., 'registry_v2.0+ranges_v2.0'
    
    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at TIMESTAMPTZ,                 -- Results validity period (e.g., 90 days)
    
    -- Constraints
    CONSTRAINT valid_result CHECK (processed_result IS NOT NULL)
);

-- Indexes for user result lookups
CREATE INDEX IF NOT EXISTS idx_bloodwork_results_user ON bloodwork_user_results (user_id);
CREATE INDEX IF NOT EXISTS idx_bloodwork_results_date ON bloodwork_user_results (test_date DESC);
CREATE INDEX IF NOT EXISTS idx_bloodwork_results_user_date ON bloodwork_user_results (user_id, test_date DESC);
CREATE INDEX IF NOT EXISTS idx_bloodwork_results_gates ON bloodwork_user_results USING GIN (active_gates);
CREATE INDEX IF NOT EXISTS idx_bloodwork_results_blocked ON bloodwork_user_results USING GIN (blocked_ingredients);

-- ============================================
-- Trigger: Auto-update updated_at
-- ============================================
CREATE OR REPLACE FUNCTION update_safety_gates_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_safety_gates_updated_at ON bloodwork_safety_gates;
CREATE TRIGGER trigger_safety_gates_updated_at
    BEFORE UPDATE ON bloodwork_safety_gates
    FOR EACH ROW
    EXECUTE FUNCTION update_safety_gates_updated_at();

-- ============================================
-- SEED DATA: All 31 Safety Gates (v2.0)
-- ============================================

INSERT INTO bloodwork_safety_gates (gate_code, gate_name, display_name, tier, action, constraint_code, description, biomarker_triggers, blocks_ingredients, cautions_ingredients, recommends_ingredients, exception_conditions)
VALUES
-- TIER 1: SAFETY GATES (14 gates)
('GATE_001', 'iron_block', 'Iron Overload Block', 'TIER1_SAFETY', 'BLOCK', 'BLOCK_IRON', 
 'Blocks iron supplementation when ferritin indicates iron overload. Deferred if acute inflammation (CRP >3.0) as ferritin is an acute phase reactant.',
 ARRAY['ferritin', 'hs_crp'], TRUE, FALSE, FALSE, '{"deferred_if": "hs_crp > 3.0"}'),

('GATE_002', 'vitamin_d_caution', 'Hypercalcemia Caution', 'TIER1_SAFETY', 'CAUTION', 'CAUTION_VITAMIN_D',
 'Cautions high-dose vitamin D when calcium is elevated to prevent hypercalcemia.',
 ARRAY['calcium_serum'], FALSE, TRUE, FALSE, NULL),

('GATE_003', 'hepatic_caution', 'Hepatotoxic Caution', 'TIER1_SAFETY', 'CAUTION', 'CAUTION_HEPATOTOXIC',
 'Cautions hepatotoxic supplements when liver enzymes are elevated. Blocks ashwagandha due to documented hepatotoxicity.',
 ARRAY['alt', 'ast'], TRUE, TRUE, FALSE, NULL),

('GATE_004', 'renal_caution', 'Renal Function Caution', 'TIER1_SAFETY', 'CAUTION', 'CAUTION_RENAL',
 'Cautions renally-cleared supplements when kidney function is impaired.',
 ARRAY['egfr', 'creatinine'], FALSE, TRUE, FALSE, NULL),

('GATE_005', 'acute_inflammation', 'Acute Inflammation Flag', 'TIER1_SAFETY', 'FLAG', 'FLAG_ACUTE_INFLAMMATION',
 'Flags acute inflammation state. Defers iron interpretation as ferritin is an acute phase reactant.',
 ARRAY['hs_crp'], FALSE, FALSE, FALSE, NULL),

('GATE_006', 'potassium_block', 'Hyperkalemia Block', 'TIER1_SAFETY', 'BLOCK', 'BLOCK_POTASSIUM',
 'Blocks potassium supplementation when serum potassium is elevated.',
 ARRAY['potassium'], TRUE, FALSE, FALSE, NULL),

('GATE_007', 'hypokalemia_support', 'Low Potassium Flag', 'TIER1_SAFETY', 'FLAG', 'FLAG_LOW_POTASSIUM',
 'Flags low potassium for potential supplementation support.',
 ARRAY['potassium'], FALSE, FALSE, TRUE, NULL),

('GATE_008', 'thyroid_iodine_block', 'Hyperthyroid Iodine Block', 'TIER1_SAFETY', 'BLOCK', 'BLOCK_IODINE',
 'Blocks iodine supplementation when TSH is suppressed (indicates hyperthyroidism).',
 ARRAY['tsh'], TRUE, FALSE, FALSE, NULL),

('GATE_009', 'thyroid_support_flag', 'Hypothyroid Support Flag', 'TIER1_SAFETY', 'FLAG', 'FLAG_THYROID_SUPPORT',
 'Flags elevated TSH for potential thyroid support (selenium, zinc, tyrosine).',
 ARRAY['tsh'], FALSE, FALSE, TRUE, NULL),

('GATE_010', 'b12_deficiency', 'B12 Deficiency Flag', 'TIER1_SAFETY', 'FLAG', 'FLAG_B12_DEFICIENCY',
 'Flags B12 deficiency for methylcobalamin supplementation priority.',
 ARRAY['vitamin_b12'], FALSE, FALSE, TRUE, NULL),

('GATE_011', 'folate_deficiency', 'Folate Deficiency Flag', 'TIER1_SAFETY', 'FLAG', 'FLAG_FOLATE_DEFICIENCY',
 'Flags folate deficiency for methylfolate supplementation priority.',
 ARRAY['folate_serum'], FALSE, FALSE, TRUE, NULL),

('GATE_012', 'homocysteine_elevated', 'Methylation Support Flag', 'TIER1_SAFETY', 'FLAG', 'FLAG_METHYLATION_SUPPORT',
 'Flags elevated homocysteine for B-vitamin methylation support (B12, folate, B6).',
 ARRAY['homocysteine'], FALSE, FALSE, TRUE, NULL),

('GATE_013', 'uric_acid_high', 'Purine Caution', 'TIER1_SAFETY', 'CAUTION', 'CAUTION_PURINE',
 'Cautions high-purine supplements when uric acid is elevated (gout risk).',
 ARRAY['uric_acid'], FALSE, TRUE, FALSE, NULL),

('GATE_014', 'coagulation_caution', 'Blood Thinning Caution', 'TIER1_SAFETY', 'CAUTION', 'CAUTION_BLOOD_THINNING',
 'Cautions blood-thinning supplements when platelet count is low.',
 ARRAY['platelet_count'], FALSE, TRUE, FALSE, NULL),

-- TIER 2: OPTIMIZATION GATES (6 gates)
('GATE_015', 'omega3_deficiency', 'Omega-3 Priority Flag', 'TIER2_OPTIMIZATION', 'FLAG', 'FLAG_OMEGA3_PRIORITY',
 'Flags omega-3 deficiency for high-priority EPA/DHA supplementation.',
 ARRAY['omega3_index'], FALSE, FALSE, TRUE, NULL),

('GATE_016', 'omega3_optimal', 'Omega-3 Sufficient Flag', 'TIER2_OPTIMIZATION', 'FLAG', 'FLAG_OMEGA3_SUFFICIENT',
 'Flags optimal omega-3 status - maintenance dosing appropriate.',
 ARRAY['omega3_index'], FALSE, FALSE, FALSE, NULL),

('GATE_017', 'zinc_copper_imbalance', 'Zinc Excess Caution', 'TIER2_OPTIMIZATION', 'CAUTION', 'CAUTION_ZINC_EXCESS',
 'Cautions additional zinc when Zn:Cu ratio is already high (copper depletion risk).',
 ARRAY['zinc_serum', 'copper_serum'], FALSE, TRUE, FALSE, NULL),

('GATE_018', 'insulin_resistance', 'Insulin Support Flag', 'TIER2_OPTIMIZATION', 'FLAG', 'FLAG_INSULIN_SUPPORT',
 'Flags insulin resistance for metabolic support (berberine, chromium, alpha-lipoic acid).',
 ARRAY['fasting_insulin', 'fasting_glucose'], FALSE, FALSE, TRUE, NULL),

('GATE_019', 'iron_deficiency_anemia', 'Iron Deficiency Anemia Flag', 'TIER2_OPTIMIZATION', 'FLAG', 'FLAG_IRON_DEFICIENCY_ANEMIA',
 'Flags iron deficiency anemia - overrides iron block when both hemoglobin and ferritin are low.',
 ARRAY['hemoglobin', 'ferritin'], FALSE, FALSE, TRUE, '{"overrides": "BLOCK_IRON"}'),

('GATE_020', 'triglyceride_caution', 'Fish Oil Dose Caution', 'TIER2_OPTIMIZATION', 'CAUTION', 'CAUTION_FISH_OIL_DOSE',
 'Cautions high-dose fish oil when triglycerides are severely elevated (>500 mg/dL) - requires medical supervision.',
 ARRAY['triglycerides'], FALSE, TRUE, FALSE, NULL),

-- TIER 3: GENETIC/HORMONAL GATES (11 gates)
('GATE_021', 'mthfr_methylfolate_required', 'Methylfolate Required', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_METHYLFOLATE_REQUIRED',
 'Requires methylfolate over folic acid due to MTHFR variants (TT homozygous or compound heterozygous).',
 ARRAY['mthfr_c677t', 'mthfr_a1298c'], TRUE, FALSE, TRUE, '{"blocks": "folic_acid"}'),

('GATE_022', 'cortisol_high', 'High Cortisol Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_CORTISOL_HIGH',
 'Flags elevated morning cortisol for stress/adrenal evaluation.',
 ARRAY['cortisol_am'], FALSE, FALSE, FALSE, NULL),

('GATE_023', 'cortisol_low', 'Adrenal Support Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_ADRENAL_SUPPORT',
 'Flags low morning cortisol for adrenal support (adaptogens, vitamin C, B5).',
 ARRAY['cortisol_am'], FALSE, FALSE, TRUE, NULL),

('GATE_024', 'dhea_low', 'DHEA Support Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_DHEA_SUPPORT',
 'Flags low DHEA-S for hormonal support consideration.',
 ARRAY['dhea_s'], FALSE, FALSE, TRUE, NULL),

('GATE_025', 'thyroid_conversion_poor', 'T4-T3 Conversion Support', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_T4_T3_CONVERSION_SUPPORT',
 'Flags poor T4 to T3 conversion (high rT3:fT3 ratio) for selenium/zinc support.',
 ARRAY['reverse_t3', 'free_t3'], FALSE, FALSE, TRUE, NULL),

('GATE_026', 'low_free_t3', 'Thyroid Support Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_THYROID_SUPPORT',
 'Flags low free T3 for thyroid optimization support.',
 ARRAY['free_t3'], FALSE, FALSE, TRUE, NULL),

('GATE_027', 'testosterone_low_male', 'Testosterone Support Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_TESTOSTERONE_SUPPORT',
 'Flags low testosterone in males for hormonal support (zinc, D3, ashwagandha if liver OK).',
 ARRAY['total_testosterone', 'free_testosterone'], FALSE, FALSE, TRUE, NULL),

('GATE_028', 'estrogen_progesterone_imbalance', 'Estrogen Dominance Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_ESTROGEN_DOMINANCE',
 'Flags estrogen dominance (high E2:P4 ratio in luteal phase) for DIM/I3C consideration.',
 ARRAY['estradiol', 'progesterone'], FALSE, FALSE, TRUE, NULL),

('GATE_029', 'apob_elevated', 'Cardiovascular Support Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_CARDIOVASCULAR_SUPPORT',
 'Flags elevated ApoB for cardiovascular support (omega-3, niacin, plant sterols).',
 ARRAY['apolipoprotein_b'], FALSE, FALSE, TRUE, NULL),

('GATE_030', 'lpa_elevated', 'Lp(a) Elevated Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_LPA_ELEVATED',
 'Flags elevated Lp(a) - genetic marker, limited intervention options (niacin may help).',
 ARRAY['lp_a'], FALSE, FALSE, TRUE, NULL),

('GATE_031', 'ggt_elevated', 'Oxidative Stress Flag', 'TIER3_GENETIC_HORMONAL', 'FLAG', 'FLAG_OXIDATIVE_STRESS',
 'Flags elevated GGT as marker of oxidative stress for antioxidant support (NAC, glutathione).',
 ARRAY['ggt'], FALSE, FALSE, TRUE, NULL)

ON CONFLICT (gate_code) DO UPDATE SET
    gate_name = EXCLUDED.gate_name,
    display_name = EXCLUDED.display_name,
    tier = EXCLUDED.tier,
    action = EXCLUDED.action,
    constraint_code = EXCLUDED.constraint_code,
    description = EXCLUDED.description,
    biomarker_triggers = EXCLUDED.biomarker_triggers,
    blocks_ingredients = EXCLUDED.blocks_ingredients,
    cautions_ingredients = EXCLUDED.cautions_ingredients,
    recommends_ingredients = EXCLUDED.recommends_ingredients,
    exception_conditions = EXCLUDED.exception_conditions,
    updated_at = NOW();

-- ============================================
-- SEED DATA: Ingredient Safety Flags
-- Maps specific ingredients to safety constraints
-- ============================================

INSERT INTO ingredient_safety_flags (ingredient_code, ingredient_name, constraint_code, flag_type, rationale)
VALUES
-- BLOCK_IRON ingredients
('iron_bisglycinate', 'Iron Bisglycinate', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin >300 ng/mL (M) or >200 ng/mL (F)'),
('iron_glycinate', 'Iron Glycinate', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin overload'),
('ferrous_sulfate', 'Ferrous Sulfate', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin overload'),
('ferrous_fumarate', 'Ferrous Fumarate', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin overload'),
('ferrous_gluconate', 'Ferrous Gluconate', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin overload'),
('carbonyl_iron', 'Carbonyl Iron', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin overload'),
('iron_amino_acid_chelate', 'Iron Amino Acid Chelate', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin overload'),
('heme_iron', 'Heme Iron Polypeptide', 'BLOCK_IRON', 'BLOCKED', 'Iron supplementation contraindicated with ferritin overload'),

-- BLOCK_POTASSIUM ingredients
('potassium_citrate', 'Potassium Citrate', 'BLOCK_POTASSIUM', 'BLOCKED', 'Potassium supplementation contraindicated with K+ >5.0 mEq/L'),
('potassium_chloride', 'Potassium Chloride', 'BLOCK_POTASSIUM', 'BLOCKED', 'Potassium supplementation contraindicated with hyperkalemia'),
('potassium_gluconate', 'Potassium Gluconate', 'BLOCK_POTASSIUM', 'BLOCKED', 'Potassium supplementation contraindicated with hyperkalemia'),
('potassium_bicarbonate', 'Potassium Bicarbonate', 'BLOCK_POTASSIUM', 'BLOCKED', 'Potassium supplementation contraindicated with hyperkalemia'),

-- BLOCK_IODINE ingredients
('iodine', 'Iodine', 'BLOCK_IODINE', 'BLOCKED', 'Iodine supplementation contraindicated when TSH <0.4 mIU/L (hyperthyroid)'),
('potassium_iodide', 'Potassium Iodide', 'BLOCK_IODINE', 'BLOCKED', 'Iodine supplementation contraindicated with hyperthyroidism'),
('kelp', 'Kelp', 'BLOCK_IODINE', 'BLOCKED', 'High iodine content contraindicated with hyperthyroidism'),
('bladderwrack', 'Bladderwrack', 'BLOCK_IODINE', 'BLOCKED', 'High iodine content contraindicated with hyperthyroidism'),

-- CAUTION_HEPATOTOXIC ingredients (includes BLOCK for ashwagandha)
('ashwagandha', 'Ashwagandha', 'CAUTION_HEPATOTOXIC', 'BLOCKED', 'Documented hepatotoxicity risk - PERMANENTLY BLOCKED per GenoMAX² safety policy'),
('kava', 'Kava', 'CAUTION_HEPATOTOXIC', 'CAUTION', 'Hepatotoxicity risk with elevated liver enzymes'),
('green_tea_extract', 'Green Tea Extract', 'CAUTION_HEPATOTOXIC', 'CAUTION', 'High-dose EGCG associated with hepatotoxicity'),
('black_cohosh', 'Black Cohosh', 'CAUTION_HEPATOTOXIC', 'CAUTION', 'Rare hepatotoxicity reports'),
('comfrey', 'Comfrey', 'CAUTION_HEPATOTOXIC', 'BLOCKED', 'Contains pyrrolizidine alkaloids - hepatotoxic'),
('chaparral', 'Chaparral', 'CAUTION_HEPATOTOXIC', 'BLOCKED', 'Documented hepatotoxicity'),
('germander', 'Germander', 'CAUTION_HEPATOTOXIC', 'BLOCKED', 'Documented hepatotoxicity'),
('niacin_ir', 'Niacin (Immediate Release)', 'CAUTION_HEPATOTOXIC', 'CAUTION', 'High-dose IR niacin associated with hepatotoxicity'),

-- CAUTION_RENAL ingredients
('creatine', 'Creatine Monohydrate', 'CAUTION_RENAL', 'CAUTION', 'May affect creatinine levels; caution with impaired renal function'),
('high_dose_vitamin_c', 'Vitamin C (High Dose)', 'CAUTION_RENAL', 'CAUTION', '>2g/day may increase oxalate; kidney stone risk with impaired function'),
('magnesium_oxide', 'Magnesium Oxide', 'CAUTION_RENAL', 'CAUTION', 'Reduced clearance with impaired renal function'),

-- CAUTION_VITAMIN_D ingredients
('vitamin_d3', 'Vitamin D3', 'CAUTION_VITAMIN_D', 'CAUTION', 'High-dose D3 may worsen hypercalcemia when calcium >10.5 mg/dL'),
('cholecalciferol', 'Cholecalciferol', 'CAUTION_VITAMIN_D', 'CAUTION', 'High-dose may worsen hypercalcemia'),

-- CAUTION_PURINE ingredients
('organ_meat_extract', 'Organ Meat Extract', 'CAUTION_PURINE', 'CAUTION', 'High purine content may elevate uric acid'),
('yeast_extract', 'Yeast Extract', 'CAUTION_PURINE', 'CAUTION', 'High purine content'),
('spirulina', 'Spirulina', 'CAUTION_PURINE', 'CAUTION', 'Contains purines; caution with elevated uric acid'),

-- CAUTION_BLOOD_THINNING ingredients
('fish_oil', 'Fish Oil', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'Mild antiplatelet effect; caution with low platelets'),
('omega3', 'Omega-3 Fatty Acids', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'Mild antiplatelet effect'),
('vitamin_e', 'Vitamin E', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'High-dose may inhibit platelet aggregation'),
('ginkgo_biloba', 'Ginkgo Biloba', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'Antiplatelet properties'),
('garlic_extract', 'Garlic Extract', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'Antiplatelet properties'),
('turmeric', 'Turmeric/Curcumin', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'May inhibit platelet aggregation'),
('nattokinase', 'Nattokinase', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'Fibrinolytic activity; significant bleeding risk'),
('bromelain', 'Bromelain', 'CAUTION_BLOOD_THINNING', 'CAUTION', 'Antiplatelet properties'),

-- CAUTION_ZINC_EXCESS ingredients
('zinc_picolinate', 'Zinc Picolinate', 'CAUTION_ZINC_EXCESS', 'CAUTION', 'Additional zinc may worsen Zn:Cu imbalance'),
('zinc_citrate', 'Zinc Citrate', 'CAUTION_ZINC_EXCESS', 'CAUTION', 'Additional zinc may worsen Zn:Cu imbalance'),
('zinc_gluconate', 'Zinc Gluconate', 'CAUTION_ZINC_EXCESS', 'CAUTION', 'Additional zinc may worsen Zn:Cu imbalance'),
('zinc_carnosine', 'Zinc Carnosine', 'CAUTION_ZINC_EXCESS', 'CAUTION', 'Additional zinc may worsen Zn:Cu imbalance'),

-- CAUTION_FISH_OIL_DOSE ingredients (for TG >500)
('fish_oil_concentrate', 'Fish Oil Concentrate', 'CAUTION_FISH_OIL_DOSE', 'CAUTION', 'High-dose fish oil with TG >500 requires medical supervision'),
('prescription_omega3', 'Prescription Omega-3', 'CAUTION_FISH_OIL_DOSE', 'CAUTION', 'Medical supervision required for severe hypertriglyceridemia'),

-- FLAG_METHYLFOLATE_REQUIRED - blocks folic acid
('folic_acid', 'Folic Acid', 'FLAG_METHYLFOLATE_REQUIRED', 'BLOCKED', 'MTHFR variants require methylfolate; folic acid may accumulate unmetabolized'),

-- RECOMMENDED ingredients by flag
('methylfolate', 'L-Methylfolate', 'FLAG_METHYLFOLATE_REQUIRED', 'RECOMMENDED', 'Active folate form for MTHFR variants'),
('methylcobalamin', 'Methylcobalamin', 'FLAG_B12_DEFICIENCY', 'RECOMMENDED', 'Active B12 form for deficiency'),
('methylcobalamin', 'Methylcobalamin', 'FLAG_METHYLATION_SUPPORT', 'RECOMMENDED', 'Supports methylation pathway'),
('pyridoxal_5_phosphate', 'P5P (Pyridoxal-5-Phosphate)', 'FLAG_METHYLATION_SUPPORT', 'RECOMMENDED', 'Active B6 supports homocysteine metabolism'),
('selenium', 'Selenium', 'FLAG_THYROID_SUPPORT', 'RECOMMENDED', 'Supports thyroid function and T4-T3 conversion'),
('selenium', 'Selenium', 'FLAG_T4_T3_CONVERSION_SUPPORT', 'RECOMMENDED', 'Essential for deiodinase enzymes'),
('zinc', 'Zinc', 'FLAG_THYROID_SUPPORT', 'RECOMMENDED', 'Supports thyroid hormone synthesis'),
('epa_dha', 'EPA/DHA', 'FLAG_OMEGA3_PRIORITY', 'RECOMMENDED', 'Priority supplementation for omega-3 deficiency'),
('berberine', 'Berberine', 'FLAG_INSULIN_SUPPORT', 'RECOMMENDED', 'Supports insulin sensitivity'),
('chromium', 'Chromium', 'FLAG_INSULIN_SUPPORT', 'RECOMMENDED', 'Supports glucose metabolism'),
('alpha_lipoic_acid', 'Alpha Lipoic Acid', 'FLAG_INSULIN_SUPPORT', 'RECOMMENDED', 'Antioxidant with insulin-sensitizing effects'),
('nac', 'N-Acetyl Cysteine', 'FLAG_OXIDATIVE_STRESS', 'RECOMMENDED', 'Glutathione precursor for oxidative stress'),
('glutathione', 'Glutathione', 'FLAG_OXIDATIVE_STRESS', 'RECOMMENDED', 'Master antioxidant'),
('dim', 'DIM (Diindolylmethane)', 'FLAG_ESTROGEN_DOMINANCE', 'RECOMMENDED', 'Supports healthy estrogen metabolism'),
('i3c', 'Indole-3-Carbinol', 'FLAG_ESTROGEN_DOMINANCE', 'RECOMMENDED', 'Supports estrogen metabolism'),
('vitamin_c', 'Vitamin C', 'FLAG_ADRENAL_SUPPORT', 'RECOMMENDED', 'Adrenal glands have high vitamin C concentration'),
('pantothenic_acid', 'Pantothenic Acid (B5)', 'FLAG_ADRENAL_SUPPORT', 'RECOMMENDED', 'Supports adrenal function'),
('adaptogens', 'Adaptogenic Herbs', 'FLAG_ADRENAL_SUPPORT', 'RECOMMENDED', 'Support stress response'),
('niacin', 'Niacin', 'FLAG_LPA_ELEVATED', 'RECOMMENDED', 'May reduce Lp(a) levels'),
('plant_sterols', 'Plant Sterols', 'FLAG_CARDIOVASCULAR_SUPPORT', 'RECOMMENDED', 'Support healthy cholesterol levels')

ON CONFLICT (ingredient_code, constraint_code) DO UPDATE SET
    ingredient_name = EXCLUDED.ingredient_name,
    flag_type = EXCLUDED.flag_type,
    rationale = EXCLUDED.rationale;

-- ============================================
-- Comments for documentation
-- ============================================
COMMENT ON TABLE bloodwork_safety_gates IS 'Master definition of all 31 v2.0 safety gates. Blood does not negotiate - deterministic constraint enforcement.';
COMMENT ON TABLE ingredient_safety_flags IS 'Maps ingredients to safety constraints (BLOCKED/CAUTION/RECOMMENDED). M:N relationship allows ingredients to have multiple flags.';
COMMENT ON TABLE bloodwork_user_results IS 'Stores processed bloodwork results per user with active gates and routing constraints.';

COMMENT ON COLUMN bloodwork_safety_gates.constraint_code IS 'Constraint code generated by BloodworkEngineV2 (e.g., BLOCK_IRON, CAUTION_HEPATOTOXIC)';
COMMENT ON COLUMN bloodwork_safety_gates.exception_conditions IS 'JSON conditions that may defer or override the gate (e.g., CRP deferring iron interpretation)';
COMMENT ON COLUMN ingredient_safety_flags.flag_type IS 'BLOCKED=hard block, CAUTION=warning/reduced dose, RECOMMENDED=prioritize for this condition';
COMMENT ON COLUMN bloodwork_user_results.ruleset_version IS 'Version string from engine: registry_v2.0+ranges_v2.0';
